### ISSUE TITLE
ACL 2017: Bibtex and style files for auto inclusion of DOIs

### ISSUE THREAD

**Issue by cfedermann** [WING-NUS/acl#20]
**S/N:** 21
**Date:** 2016-09-09
**Priority:** Medium
**Title:** ACL 2017: Bibtex and style files for auto inclusion of DOIs

**Comment by danielgildea** [comment]
Here is a proposed set of style files to provide links to DOIs in the References section.

It is based on the Latex hyperref package.  If the bibtex contains a DOI field, the
title of the paper in the References section will be a link to the DOI, but the DOI does not
appear as text, following how the CL journal currently handles DOI links.
Because we include the hyperref package, Latex references to tables, 
figures, etc, within the paper will also become hyperref references.  Use of hyperref
can be disabled by saying:
\usepackage[nohyperref]{acl2017}

To make the style files compatible with hyperref, I ripped out the custom definitions of ACL's citation
commands and replaced them with the standard natbib package.  You can now use
any natbib commands for citations in the text, as well as the \newcite and \shortcite
commands that were defined in older ACL style files.

[acl2017.zip](https://github.com/WING-NUS/acl/files/560376/acl2017.zip)

**Comment by knmnyn** [comment]
Hi Dan, all:

I have made significant edits to the acl_natbib file and the accompanying demonstration files acl2017.tex and acl2017.bib to change:

- added visible DOI hyperlink, in addition to the title being hyperlinked.
- added examples in the sample document and adjusted documentation accordingly.
- changed the DOI URL pattern from the deprecated http://dx.doi.org format to the https://doi.org format.
- added ACL Anthology Identifier URLs and hyperlinks when they are available, but only when the DOI is not available.
[acl2017v2.zip](https://github.com/WING-NUS/acl/files/634219/acl2017v2.zip)

As this is now done, I'm closing this issue, and will mail the appropriate parties about this.

**Comment by danielgildea** [comment]
Here is a minor update to prevent bibtex from printing an error message, and returning an error code,
when there is no DOI in a bibtex entry.

[acl2017v3.zip](https://github.com/WING-NUS/acl/files/641488/acl2017v3.zip)
