### ISSUE TITLE
"Page doesn't exist" errors when searching by author name

### ISSUE THREAD

**Issue by buechel** [WING-NUS/acl#32]
I doubt this issue is not know but I couldn't find it in the issue list here on github:

When I search for an author by name, quite often I get "The page you were looking for doesn't exist." errors even though, there are papers by this author in the anthology. E.g. when looking for Hannah Rashkin (see Screenshot) I get this error, but there is a paper by her: http://aclanthology.info/papers/connotation-frames-a-data-driven-investigation.bib

![acl anthology](https://cloud.githubusercontent.com/assets/12396704/22975631/b7a2f4e8-f387-11e6-9052-66d09885740a.png)

**Comment by knmnyn** [comment]
Hi @buechel , thanks for your error report, we appreciate the notification.  Even when we know of the issue, it's good to get a formal error report until it is fixed.

This problem was caused by the database being updated but the search indices being out of date.  We have currently fixed this problem and hope to have a better solution for it in the long run.  

Thank you!
